version = 4.2.0
archive_dir = /etc/letsencrypt/archive/ostracon.ru
cert = /etc/letsencrypt/live/ostracon.ru/cert.pem
privkey = /etc/letsencrypt/live/ostracon.ru/privkey.pem
chain = /etc/letsencrypt/live/ostracon.ru/chain.pem
fullchain = /etc/letsencrypt/live/ostracon.ru/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 127d7e40af6a4dd71f30d152efc4e01b
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
ostracon.ru = /var/www/certbot
