site_name: api
site_description: Student work assessment service
repo_url: https://github.com/mrsalbey/review_api
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/mrsalbey">mrsalbey</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
