# Generated by Django 5.2 on 2025-08-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewcategory",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name="slug"),
        ),
    ]
